// EN lang variables

tinyMCE.addI18n('en.delightform',{
title: 'Edit forms',

style_none: 'no style',
style_tiny: 'tiny',
style_small: 'small',
style_medium: 'medium',
style_large: 'large',

control_name: 'Name:',
control_desc: 'Description:',
control_size: 'Size:',
control_value: 'Default value:',

validation: 'Validation: ',
valid_text: 'text (no validation)',
valid_number: 'number',
valid_email: 'e-mail',
valid_mandatory: 'Mandatory: ',

namemandatory: 'Name is mandatory.',
nameunique: 'There is already a control of the same name.',
valuemandatory: 'Value is mandatory.',

edit: 'Edit field',
edit_title: 'Edit field',
edit_legend: 'Insert edit field:',
edit_type: 'Type:',
edit_single: 'single-line',
edit_multi: 'multi-line',
edit_password: 'password',
edit_file: 'file',

checkbox: 'Checkbox',
checkbox_title: 'Checkbox',
checkbox_legend: 'Insert checkbox:',
checkbox_checked: 'Checked:',
checkbox_value: 'Value:',

radio: 'Radio',
radio_title: 'Radio',
radio_legend: 'Insert radio:',
radio_mode: 'Editing mode: ',
radio_new: 'New',
radio_existing: 'Existing',
radio_default: 'Default selected',
radio_default_this: 'this',
radio_default_none: 'none',
radio_value: 'Value:',

button: 'Button',
button_title: 'Button',
button_legend: 'Insert button: ',
button_type: 'Type:',
button_submit: 'Send',
button_reset: 'Delete',
button_value: 'Button description: ',

select: 'Select',
select_title: 'Select',
select_legend: 'Insert select:',
select_options: 'Select items:',
select_add_option: 'Add&nbsp;item',
select_sort_priority: 'Sort&nbsp;by&nbsp;priority',
select_sort_value: 'Sort&nbsp;by&nbsp;value',
select_sort_text: 'Sort&nbsp;by&nbsp;caption',
option_value: 'Value',
option_text: 'Caption',
option_priority: 'Priority',

config: 'Configure Formular',
config_title: 'Configure Formular',
config_tab1: 'Global Settings',
config_tab2: 'Formular Settings',
config_tab3: 'Tracking-Server Settings',
config_legend_tab1: 'Global Settings',
config_legend_tab12: 'Enhanced Settings',
config_legend_tab13: 'Mandatory Fields',
config_legend_tab2: 'EMail Settings',
config_legend_tab21: 'Texts',
config_legend_tab3: 'Tracking-Server Settings',
config_legend_tab31: 'Newsletter-Tracking Settings',
config_legend_tab32: 'Formular-Tracking Settings',
config_formtype: 'Formular-Typ',
config_formtype_mail: 'Send Data over EMail',
config_formtype_tracking: 'Send Data through delight Tracking-Server',
config_formname: 'Formula Name',
config_formsuccess: 'Redirect to URL on Success',
config_formfailed: 'Redirect to URL on Error',
config_encoding: 'Encoding',
config_encoding1: 'application/x-www-form-urlencoded',
config_formvalidate: 'Check for Mandatory Fields',
config_formvalidate1: 'Yes',
config_formvalidate0: 'No',
config_typemail_rcpt: 'Recipient EMail-Address',
config_typemail_rcpt_field: 'Recipient-Select field',
config_typemail_rcpt_field_hint: 'What\'s this?',
config_typemail_rcpt_field_descr: 'To let the User decide, who the receiver is, you can define a comma seperated list in the "Recipient EMail-Address" (above) where each email address ha a prefixed integer, followed by a colon:<br/><b>0:email@domain.dom, 1:second@email.dom, 2:third@other.dom</b><br/><br/>Then you can add a Select on your Formular where each entry identifies one recipient. Don\'t write the EMail-Address as value in the Select, the value and the index you defined in the Recipients-List must match.<br/><br/>That way, neither an EMail-Address is on the site and none is sent to the server.',
mailrcptfield_field_none: 'No Recipient-List',
config_typemail_server: 'Email server and port',
config_typemail_port: 'Port',
config_typemail_auth: 'Authentication',
config_typemail_authnone: 'None',
config_typemail_authplain: 'PLAIN',
config_typemail_authlogin: 'LOGIN',
config_typemail_username: 'Username',
config_typemail_password: 'Password',
config_typemail_rcptname: 'Name or Company',
config_typemail_subject: 'Subject',
config_typemail_inform: 'Send the EMail also to the User',
config_typemail_inform1: 'Yes',
config_typemail_inform0: 'No',
config_typemail_senderfield: 'Field in which the User writes the EMail-Address',
config_typemail_senderfieldnone: 'no EMail-Field',
config_typemail_pretext: 'Introduction Text<br/><em>(Values from Formular-Fields can be used by <b>[FormularFieldName]</b>)</em>',
config_typemail_posttext: 'Closing Paragraph<br/><em>(Values from Formular-Fields can be used by <b>[FormularFieldName]</b>)</em>',
config_typemail_attachment: 'EMail-Attachment',
config_typemail_attachment_none: 'No Data attached',
config_typemail_attachment_csv: 'Attach Data as CSV for Tablecalculation program',
config_typemail_attachment_vcard: 'Attach Data as VCard for Address-Administration program',
config_typemail_attachment_vcard_hint: 'VCard-Info',
config_typemail_attachment_vcard_hint_msg: 'A VCard uses following fieldnames: street, city, region, plz, country, street_work, city_work, region_work, plz_work, country_work, title, prefix, firstname, middlename, lastname, birthday, organization, role, website, email, telephone, telefax, email_XY, tel_XY. XY steht für den Typen WORK, HOME, etc. All other fields are written into the Notes of the VCard.',
config_typetracking_server : 'Tracking-Server',
config_typetracking_account : 'Your ID on the Tracking-Server',
config_typetracking_module : 'Modul/Channel',
config_tracking_mnewsletter : 'Newsletter Registration',
config_tracking_mformular : 'Formular-Data',
config_typetracking_formname : 'Formular Name/Container on the TrackingServer',
config_typetracking_server_hint : 'Only the Domain. Sample: "deponat.ch"',
config_typetracking_account_hint : 'Write here your UserID you have registered. The UserID you also use on Login and in delight crm/email for fetching data',
config_mandatory_text_string : 'String for Textfields',
config_mandatory_text_color : 'Colorize Textfields',
config_mandatory_number_string : 'String for Numberfields',
config_mandatory_number_color : 'Colorize Numberfields',
config_mandatory_email_string : 'String for EMail-Fields',
config_mandatory_email_color : 'Colorize EMail-Fields',

nonsens:''
});
