tinyMCE.addI18n('de.admin_dlg',{
	image_name : 'Name',
	image_dimension : 'Abmessungen',
	image_date : 'Datum',
	image_size : 'Gr\u00F6sse',
	image_upload : 'Bild importieren',
	image_delete : 'Bild l\u00F6schen',
	image_replace : 'Bild ersetzen',
	image_text : 'Bildbeschreibung bearbeiten',
	image_title : 'Bildtitel definieren',
	
	file_name : 'Dateiname',
	file_downloaded : 'Downloads',
	file_mime : 'Dateityp',
	file_date : 'Datum',
	file_link : 'Download-Link',
	file_size : 'Gr\u00F6sse',
	file_last : 'Zuletzt am:',
	file_upload : 'Datei importieren',
	file_delete : 'Datei l\u00F6schen',
	file_replace : 'Datei ersetzen',
	file_text : 'Dateibeschreibung bearbeiten',
	file_title : 'Dateititel definieren',
	
	section_new : 'Neuen Bereich anlegen',
	section_delete : 'Bereich l\u00F6schen',
	section_edit : 'Bereich umbenennen',
	section_delete_question : 'Soll der Bereich wirklich gel\u00F6scht werden?\nAlle Daten und Unterbereiche werden ebenfalls gel\u00F6scht.\n\nBereich: ',
	section_secure : 'Bereich absichern',
	
	upload_file : 'Lokale Dateien',
	upload_ftp : 'FTP-Dateien',
	upload_ctrl_hint : 'F\u00FCr Mehrfach-Auswahl CTRL-Taste gedr\u00FCckt halten',
	upload_delete_question : 'Soll der Eintrag wirklich entfernt werden? Der Vorgang kann nicht mehr r\u00FCckg\u00E4ngig gemacht werden.',
	upload_html5_hint : 'Sie können durch drücken der Ctrl/Strg Taste mehrere Dateien auswählen, oder einfach mehrere male auf Durchsuchen klicken und eine Datei auswählen.',
	upload_html5_text : 'Ziehen Sie die gewollten Dateien direkt mit der Maus auf in dieses Fenster oder benutzen Sie das obige Auswahlfeld.',
	upload_html5_waiting : 'Warte auf das Hochladen...',
	upload_html5_finished : 'Hochgeladen',
	
	news_create : 'News erstellen',
	news_edit : 'News bearbeiten',
	news_delete : 'News l\u00F6schen',
	news_changedate : 'Datum \u00E4ndern',
	news_addrss : 'RSS-Feed einbinden',
	
	static_langname : 'Sprache',
	static_langshort : 'Abk\u00FCrzung',
	static_langcharset : 'Zeichensatz',
	static_sitescountold : 'Anzahl Seiten aktuell',
	static_sitescount : 'Anzahl neue Seiten',
	static_sitescreated : 'Seiten erstellt',
	static_sitespending : 'Seiten ausstehend',
	static_timeelapsed : 'Zeit vergangen',
	static_timepending : 'Zeit ausstehend',
	static_progress : 'Fortschritt',
	static_create : 'Starten',
	static_cancel : 'Abbrechen',
	static_pleasewait : 'Daten werden gesammelt, bitte warten...',
	static_finished : 'Vorgang beendet',

	user_groups : 'Gruppe hinzuf\u00FCgen',
	user_group_delete : 'l\u00F6schen',
	user_group_delete_question : 'Soll die Gruppe wirklich gel\u00F6scht werden?',
	user_group_edit : 'bearbeiten',
	user_usernumber : 'Benutzernummer',
	user_username : 'Benutzername',
	user_title : 'Anrede',
	user_lastname : 'Vorname',
	user_surname : 'Name',
	user_address : 'Adresse',
	user_zip : 'Postleitzahl',
	user_city : 'Stadt',
	user_company : 'Firma',
	user_password : 'Passwort',
	
	content_save :'Speichern',
	content_delete :'Aktiven Wert l\u00F6schen',
	content_new :'Neuen Wert einf\u00FCgen',
	content_type_0: 'Zahl',
	content_type_1: 'Textzeile',
	content_type_2: 'Dezimal',
	content_type_3: 'Bild',
	content_type_4: 'Datei',
	content_type_5: 'News',
	content_type_6: 'Text',
	content_type_7: 'Farbe',
	content_type_8: 'HTML',
	open_administration : 'Administration \u00F6ffnen',
	tab_settings : 'Einstellungen',
	tab_layout : 'Aussehen',
	tab_list : 'Liste',
	settings_panel_title : 'Einstellungen',
	title_panel_title : '\u00DCberschrift',
	title_panel_title_hint : 'Durch Wort "default" wird automatisch der Name des Ordners angezeigt. Soll kein Titel angezeigt werden, kann dieses Feld einfach geleert werden.',
	layout_panel_title : 'Darstellungsart w\u00E4hlen',
	list_panel_title : 'Eintrag w\u00E4hlen',
	
	option_show_recursive : 'Eintr\u00E4ge aus Unterbereichen zeigen',
	option_show_number : 'Anzahl Eintr\u00E4ge',
	option_show_section : 'Zeige Bereiche',
	option_show_title : 'Titel anzeigen',
	option_show_description : 'Beschreibung anzeigen',
	option_show_data : 'Daten anzeigen',
	option_title : 'Gr\u00F6sse des Titels',
	
	group_content : 'Texte',
	group_assigned : 'Texte in der Gruppe',
	group_unassigned : 'Verf\u00FCgbare Texte',
	group_content_panel_title : 'Texte f\u00FCr Gruppierung w\u00E4hlen',
	
	iframe_url : 'Internet-Adresse (URL)',
	option_show_width : 'Breite des Anzeigebereiches',
	option_show_height : 'H\u00F6he des Anzeigebereiches',
	option_width_unit : 'Masseinheit der Breite',
	option_height_unit : 'Masseinheit der H\u00F6he',
	
	recursive : 'Inklusive Unterseiten',
	value : 'Wert',
	menu : 'Seite',
	settings : 'Einstellungen',
	setting_for: 'Einstellung f\u00FCr',
	comment: 'Bitte beachten',
	no_value_given : 'Bitte geben Sie einen Wert ein.',
	no_menu_given : 'Bitte w\u00E4hlen Sie ein Men\u00FC aus.',
	on_all_sites : 'Auf allen Seiten',
	
	gtext_create : 'Text erstellen',
	gtext_delete : 'Text l\u00F6schen',
	gtext_edit : 'Text bearbeiten',
	
	sort_content : 'Sortieren',
	sort_name : 'nach name',
	sort_title : 'nach Titel',
	sort_date : 'nach Datum',
	
	last:''
});

// o -> \u00F6 \u00D6
// u -> \u00FC \u00DC
// a -> \u00E4 \u00C4