tinyMCE.addI18n('en.admin_dlg',{
	image_name : 'Name',
	image_dimension : 'Dimension',
	image_date : 'Date',
	image_size : 'Size',
	image_upload : 'Import Image',
	image_delete : 'Delete Image',
	image_replace : 'Replace Image',
	image_text : 'Change Image-Text',
	image_title : 'Change Image-Title',
	
	file_name : 'Filename',
	file_downloaded : 'Downloads',
	file_mime : 'Filetype',
	file_date : 'Date',
	file_link : 'Download-Link',
	file_size : 'Size',
	file_last : 'Last on:',
	file_upload : 'Import File',
	file_delete : 'Delete File',
	file_replace : 'Replace File',
	file_text : 'Change File-Text',
	file_title : 'Change File-Title',
	
	section_new : 'Create new Folder',
	section_delete : 'Delete Folder',
	section_edit : 'Rename Folder',
	section_delete_question : 'Really delete this Folder?\nAll containing Data and Subfolders will be deleted also.\n\nFolder: ',
	section_secure : 'Secure selected section',
	
	upload_file : 'Local Files',
	upload_ftp : 'FTP-Files',
	upload_ctrl_hint : 'Hold down CTRL-Key to choose more than one Entry',
	upload_delete_question : 'Really delete this File?\nYou can not undo this action.',
	upload_html5_hint : 'Press Ctrl to select more than only one file at once or just click the browse button more than one tme and select an other file each time.',
	upload_html5_text : 'Drag and Drop your Files directly to this Area or select multiple ones with the input.',
	upload_html5_waiting : 'Waiting for uploading to start...',
	upload_html5_finished : 'Uploaded',
	
	news_create : 'Create News',
	news_edit : 'Change News',
	news_delete : 'Delete News',
	news_changedate : 'Change News-Date',
	news_addrss : 'Include RSS-Feed',
	
	static_langname : 'Language',
	static_langshort : 'Short',
	static_langcharset : 'Charset',
	static_sitescountold : 'Num current pages',
	static_sitescount : 'Num new pages',
	static_sitescreated : 'Created Pages',
	static_sitespending : 'Pending Pages',
	static_timeelapsed : 'Time Elapsed',
	static_timepending : 'Time Pending',
	static_progress : 'Progress',
	static_create : 'Start',
	static_cancel : 'Cancel',
	static_pleasewait : 'Please wait while collecting data...',
	static_finished : 'Process ended',

	user_groups : 'Add Group',
	user_group_delete : 'remove',
	user_group_delete_question : 'Really delete this Group',
	user_group_edit : 'change',
	user_usernumber : 'Usernumber',
	user_username : 'Username',
	user_title : 'Title',
	user_lastname : 'Lastname',
	user_surname : 'Surname',
	user_address : 'Address',
	user_zip : 'Postalcode',
	user_city : 'City',
	user_company : 'Company',
	user_password : 'Password',
	
	content_save :'Save',
	content_delete :'Delete active Configuration',
	content_new :'Insert new Configuration',
	content_type_0: 'Number',
	content_type_1: 'String',
	content_type_2: 'Decimal',
	content_type_3: 'Image',
	content_type_4: 'File',
	content_type_5: 'News',
	content_type_6: 'Text',
	content_type_7: 'Color',
	content_type_8: 'HTML',
	open_administration : 'Open Administration',
	tab_settings : 'Settings',
	tab_layout : 'Look and feel',
	tab_list : 'List',
	settings_panel_title : 'Settings',
	title_panel_title : 'Title',
	title_panel_title_hint : 'The word "default" shows the Sectionname. If no title should be shown, just empty this field.',
	layout_panel_title : 'Choose how the Content should be presented',
	list_panel_title : 'Choose an Entry',
	
	option_show_recursive : 'Show entries from Subfolders too',
	option_show_number : 'Num entries',
	option_show_section : 'Show Folders',
	option_show_title : 'Show Title',
	option_show_description : 'Show Description',
	option_show_data : 'Show Data',
	option_title : 'Size of the Title',
	
	group_content : 'Texts',
	group_assigned : 'Textblocks in this Group',
	group_unassigned : 'Available Textblocks',
	group_content_panel_title : 'Assign available Textblocks to this Group',
	
	iframe_url : 'Internet-Adress (URL)',
	option_show_width : 'Width of the Frame',
	option_show_height : 'Height of the Frame',
	option_width_unit : 'Scale Unit for Width',
	option_height_unit : 'Scale Unit for Height',
	
	recursive : 'Including Subsites',
	value : 'Value',
	menu : 'Site',
	settings : 'Settings',
	setting_for: 'Settings for',
	comment: 'Please Note',
	no_value_given : 'Please enter a value.',
	no_menu_given : 'Please choose a menu.',
	on_all_sites : 'On all Sites',
	
	gtext_create : 'Create new Text',
	gtext_delete : 'Delete text',
	gtext_edit : 'Edit Text',
	
	sort_content : 'Sort Entries',
	sort_name : 'by Name',
	sort_title : 'by Title',
	sort_date : 'by Date',
	
	last:''
});

// a -> \u00F6
// o -> \u00FC
// u -> \u00E4