// EN lang variables

tinyMCE.addI18n('en.delightform',{
title: 'Edit forms',

style_none: 'no style',
style_tiny: 'tiny',
style_small: 'small',
style_medium: 'medium',
style_large: 'large',

control_name: 'Name:',
control_desc: 'Description:',
control_size: 'Size:',
control_value: 'Default value:',

validation: 'Validation: ',
valid_text: 'text (no validation)',
valid_number: 'number',
valid_email: 'e-mail',
valid_mandatory: 'Mandatory: ',

err_name_mandatory: 'Name is mandatory.',
err_name_unique: 'There is already a control of the same name.',
err_value_mandatory: 'Value is mandatory.',

edit: 'Edit field',
edit_title: 'Edit field',
edit_legend: 'Insert edit field:',
edit_type: 'Type:',
edit_single: 'single-line',
edit_multi: 'multi-line',
edit_password: 'password',
edit_file: 'file',

checkbox: 'Checkbox',
checkbox_title: 'Checkbox',
checkbox_legend: 'Insert checkbox:',
checkbox_checked: 'Checked:',
checkbox_value: 'Value:',

radio: 'Radio',
radio_title: 'Radio',
radio_legend: 'Insert radio:',
radio_mode: 'Editing mode: ',
radio_new: 'New',
radio_existing: 'Existing',
radio_default: 'Default selected',
radio_default_this: 'this',
radio_default_none: 'none',
radio_value: 'Value:',

button: 'Button',
button_title: 'Button',
button_legend: 'Insert button: ',
button_type: 'Type:',
button_submit: 'Send',
button_reset: 'Delete',
button_value: 'Button description: ',

select: 'Select',
select_title: 'Select',
select_legend: 'Insert select:',
select_options: 'Select items:',
select_add_option: 'Add&nbsp;item',
select_sort_priority: 'Sort&nbsp;by&nbsp;priority',
select_sort_value: 'Sort&nbsp;by&nbsp;value',
select_sort_text: 'Sort&nbsp;by&nbsp;caption',
option_value: 'Value',
option_text: 'Caption',
option_priority: 'Priority',

fieldset: 'Fieldset',
fieldset_title: 'Fieldset',
fieldset_legend: 'Insert fieldset',
fieldset_label: 'Title:',
unfieldset: 'Clear fieldset',

config: 'Configure Formular',
config_title: 'Configure Formular',
config_tab1: 'Allgemeine Einstellungen',
config_tab2: 'Einstellungen zum Formular-Typ',
config_legend_tab1: 'Allgemeine Einstellungen',
config_legend_tab12: 'Erweiterte Einstellungen',
config_formtype: 'Formular-Typ',
config_formtype_mail: 'Daten per E-Mail versenden',
config_formname: 'Name des Formulars',
config_formsuccess: 'Weiterleitung zu URL bei Erfolg',
config_formfailed: 'Weiterleitung zu URL bei einem Fehler',
config_encoding: 'Format zum Senden der Daten (Encoding)',
config_encoding1: 'application/x-www-form-urlencoded',
config_formvalidate: 'Sollen die Eingabefelder gepr&uuml;ft werden',
config_formvalidate1: 'Ja',
config_formvalidate0: 'Nein',
config_legend_tab2: 'Einstellungen zum gew&auml;hlten Formular-Typen',
config_typemail_rcpt: 'E-Mail Adresse des Empf&auml;ngers',
config_typemail_rcptname: 'Name und/oder Firma des Empf&auml;ngers',
config_typemail_subject: 'Betreff f&uuml;r das E-Mail',
config_typemail_inform: 'Das Mail auch dem Besucher zustellen (N&auml;chste Einstellung beachten)',
config_typemail_inform1: 'Ja',
config_typemail_inform0: 'Nein',
config_typemail_senderfield: 'Besucher schreibt E-Mail Adresse in dieses Feld',
config_typemail_senderfieldnone: 'kein E-Mail Feld',
config_typemail_pretext: 'Einleitender Text im E-Mail<br/><em>(Auf Formularelder kann mittels <b>[FormularFeldName]</b> zugegriffen werden)</em>',
config_typemail_posttext: 'Abschliessender Text im E-Mail<br/><em>(Auf Formularelder kann mittels <b>[FormularFeldName]</b> zugegriffen werden)</em>',
config_typetracking_server : 'Tracking-Server URL',
config_typetracking_account : 'Identity on TrackingServer',
config_typetracking_module : 'Modul/Channel',
config_tracking_mnewsletter : 'Newsletter registration',
config_tracking_mformular : 'Save FormularData',


nonsens: ''
});
